baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'mental clutter'
theme = 'hugo-book'

[params]
  author = "Your Name"
  description = "A Hugo Book site example"
  
[menu]
  [[menu.main]]
    identifier = "docs"
    name = "Docs"
    url = "/docs/"
    weight = 1
